#KubeJS Dev Properties
#Wed May 27 03:38:24 JST 2026
logSkippedTags=false
logSkippedRecipes=false
logSkippedPlugins=true
debugInfo=true
strictTags=false
logAddedRecipes=false
logRemovedRecipes=false
logModifiedRecipes=false
logInvalidRecipeHandlers=true
dataPackOutput=false
logGeneratedData=false
logErroringRecipes=true
alwaysCaptureErrors=false
